apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
  namespace: elk-logging
data:
  elasticsearch.yml: |
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
    xpack.license.self_generated.type: trial
    node.max_local_storage_nodes: 1
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
  role_mapping.yml: |