apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  namespace: elk-logging
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch:9200
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: Username
    elasticsearch.password: Password