apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    component: logstash
spec:
  type: ClusterIP
  selector:
    component: logstash
  ports:
  - name: http
    port: 80
    targetPort: http